---
new_page_extension: md
auto_deploy: true
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: works
  label: Works
  create: all
  match: "**/*/[!index]*"
  templates:
  - works
- type: directory
  path: journal
  label: Journal
  create: all
  match: "**/*/[!index]"
  templates:
  - journal
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
